apiVersion: v1
kind: Pod 
metadata:
    name: myapp-pod
spec:
    containers:
        - name: data-processor
          image: data-processor
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
                  - Medium


apiVersion: v1
kind: Pod 
metadata:
    name: myapp-pod
spec:
    containers:
        - name: data-processor
          image: data-processor
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - Small


apiVersion: v1
kind: Pod 
metadata:
    name: myapp-pod
spec:
    containers:
        - name: data-processor
          image: data-processor
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: # Node Affinity Type
          nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: Exists


******Node Affinity Types*****

***Available

requiredDuringSchedulingIgnoreDuringExecution
- the Pod will only be associate with the node who has the specified selector During Scheduling
- If the label Node change, the pod will remain on the Node

preferredDuringSchedulingIgnoreDuringExecution
- the Pod will PREFER to be associate with the node who has the specified selector During Scheduling
- If the pod cannot select the spcify node, then it will choose another one
- If the label Node change, the pod will remain on the Node

***Planned

requiredDuringSchedulingRequiredDuringExecution
- the Pod will only be associate with the node who has the specified selector During Scheduling
- If the label Node change, the pod will be evicted

preferredDuringSchedulingRequiredDuringExecution
- the Pod will PREFER to be associate with the node who has the specified selector During Scheduling
- If the pod cannot select the spcify node, then it will choose another one
- If the label Node change, the pod will be evicted