apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi



# kubectl create -f persistent-volume-claim.yaml
# kubectl get persistentvolumeclaim

# kubectl delete persistentvolumeclaim myclaim

# kubectl edit persistentvolumeclaim mysql-pvc