apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: ngnix-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end

#kubectl apply -f deployment.yaml
#kubectl set image
#kubectl rollout undo deployment/myapp-deployment
#kubectl rollout status deployment/myapp-deployment
#kubectl get deployments
#kubectl rollout history deployments