apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: ngnix-container
      image: nginx


# kubectl create -f pod-definition.yaml
# kubectl get pods