apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data: 
  APP_COLOR: blue
  APP_MODE: prod 

# kubectl create -f config-map.yaml
# kubectl get configmaps
# kubectl get cm
# kubectl describe configmaps


# kubectl create configmap <config-name> --from-literal=<key>=<value>
# kubectl create configmap app_config --from-literal=APP_COLOR=blue \
                                     #--from-literal=APP_MOD=prod

# kubectl create configmap <config-name> --from-file=<path-to-file>
# kubectl create configmap app_config --from-file=app_config.properties